// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fbs
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct C2S_CONNECT_REQ : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static C2S_CONNECT_REQ GetRootAsC2S_CONNECT_REQ(ByteBuffer _bb) { return GetRootAsC2S_CONNECT_REQ(_bb, new C2S_CONNECT_REQ()); }
  public static C2S_CONNECT_REQ GetRootAsC2S_CONNECT_REQ(ByteBuffer _bb, C2S_CONNECT_REQ obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public C2S_CONNECT_REQ __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(4); }

  public static Offset<fbs.C2S_CONNECT_REQ> CreateC2S_CONNECT_REQ(FlatBufferBuilder builder,
      StringOffset nameOffset = default(StringOffset)) {
    builder.StartTable(1);
    C2S_CONNECT_REQ.AddName(builder, nameOffset);
    return C2S_CONNECT_REQ.EndC2S_CONNECT_REQ(builder);
  }

  public static void StartC2S_CONNECT_REQ(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(0, nameOffset.Value, 0); }
  public static Offset<fbs.C2S_CONNECT_REQ> EndC2S_CONNECT_REQ(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<fbs.C2S_CONNECT_REQ>(o);
  }
}


static public class C2S_CONNECT_REQVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*Name*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
