// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fbs
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct C2S_LEAVE_REQ : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static C2S_LEAVE_REQ GetRootAsC2S_LEAVE_REQ(ByteBuffer _bb) { return GetRootAsC2S_LEAVE_REQ(_bb, new C2S_LEAVE_REQ()); }
  public static C2S_LEAVE_REQ GetRootAsC2S_LEAVE_REQ(ByteBuffer _bb, C2S_LEAVE_REQ obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public C2S_LEAVE_REQ __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartC2S_LEAVE_REQ(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<fbs.C2S_LEAVE_REQ> EndC2S_LEAVE_REQ(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<fbs.C2S_LEAVE_REQ>(o);
  }
}


static public class C2S_LEAVE_REQVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
