// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fbs
{

public enum Packet : byte
{
  NONE = 0,
  C2S_CONNECT_REQ = 1,
  S2C_CONNECT_RES = 2,
  C2S_ENTER_REQ = 3,
  S2C_ENTER_RES = 4,
  C2S_USERLIST_REQ = 5,
  S2C_USERLIST_RES = 6,
  C2S_LEAVE_REQ = 7,
  S2C_LEAVE_RES = 8,
  C2S_CHAT_REQ = 9,
  S2C_CHAT_RES = 10,
};



static public class PacketVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, byte typeId, uint tablePos)
  {
    bool result = true;
    switch((Packet)typeId)
    {
      case Packet.C2S_CONNECT_REQ:
        result = fbs.C2S_CONNECT_REQVerify.Verify(verifier, tablePos);
        break;
      case Packet.S2C_CONNECT_RES:
        result = fbs.S2C_CONNECT_RESVerify.Verify(verifier, tablePos);
        break;
      case Packet.C2S_ENTER_REQ:
        result = fbs.C2S_ENTER_REQVerify.Verify(verifier, tablePos);
        break;
      case Packet.S2C_ENTER_RES:
        result = fbs.S2C_ENTER_RESVerify.Verify(verifier, tablePos);
        break;
      case Packet.C2S_USERLIST_REQ:
        result = fbs.C2S_USERLIST_REQVerify.Verify(verifier, tablePos);
        break;
      case Packet.S2C_USERLIST_RES:
        result = fbs.S2C_USERLIST_RESVerify.Verify(verifier, tablePos);
        break;
      case Packet.C2S_LEAVE_REQ:
        result = fbs.C2S_LEAVE_REQVerify.Verify(verifier, tablePos);
        break;
      case Packet.S2C_LEAVE_RES:
        result = fbs.S2C_LEAVE_RESVerify.Verify(verifier, tablePos);
        break;
      case Packet.C2S_CHAT_REQ:
        result = fbs.C2S_CHAT_REQVerify.Verify(verifier, tablePos);
        break;
      case Packet.S2C_CHAT_RES:
        result = fbs.S2C_CHAT_RESVerify.Verify(verifier, tablePos);
        break;
      default: result = true;
        break;
    }
    return result;
  }
}


}
