// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fbs
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Root : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static Root GetRootAsRoot(ByteBuffer _bb) { return GetRootAsRoot(_bb, new Root()); }
  public static Root GetRootAsRoot(ByteBuffer _bb, Root obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyRoot(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, RootVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Root __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public fbs.Packet PacketType { get { int o = __p.__offset(4); return o != 0 ? (fbs.Packet)__p.bb.Get(o + __p.bb_pos) : fbs.Packet.NONE; } }
  public TTable? Packet<TTable>() where TTable : struct, IFlatbufferObject { int o = __p.__offset(6); return o != 0 ? (TTable?)__p.__union<TTable>(o + __p.bb_pos) : null; }
  public fbs.C2S_CONNECT_REQ PacketAsC2S_CONNECT_REQ() { return Packet<fbs.C2S_CONNECT_REQ>().Value; }
  public fbs.S2C_CONNECT_RES PacketAsS2C_CONNECT_RES() { return Packet<fbs.S2C_CONNECT_RES>().Value; }
  public fbs.C2S_ENTER_REQ PacketAsC2S_ENTER_REQ() { return Packet<fbs.C2S_ENTER_REQ>().Value; }
  public fbs.S2C_ENTER_RES PacketAsS2C_ENTER_RES() { return Packet<fbs.S2C_ENTER_RES>().Value; }
  public fbs.C2S_USERLIST_REQ PacketAsC2S_USERLIST_REQ() { return Packet<fbs.C2S_USERLIST_REQ>().Value; }
  public fbs.S2C_USERLIST_RES PacketAsS2C_USERLIST_RES() { return Packet<fbs.S2C_USERLIST_RES>().Value; }
  public fbs.C2S_LEAVE_REQ PacketAsC2S_LEAVE_REQ() { return Packet<fbs.C2S_LEAVE_REQ>().Value; }
  public fbs.S2C_LEAVE_RES PacketAsS2C_LEAVE_RES() { return Packet<fbs.S2C_LEAVE_RES>().Value; }
  public fbs.C2S_CHAT_REQ PacketAsC2S_CHAT_REQ() { return Packet<fbs.C2S_CHAT_REQ>().Value; }
  public fbs.S2C_CHAT_RES PacketAsS2C_CHAT_RES() { return Packet<fbs.S2C_CHAT_RES>().Value; }

  public static Offset<fbs.Root> CreateRoot(FlatBufferBuilder builder,
      fbs.Packet packet_type = fbs.Packet.NONE,
      int packetOffset = 0) {
    builder.StartTable(2);
    Root.AddPacket(builder, packetOffset);
    Root.AddPacketType(builder, packet_type);
    return Root.EndRoot(builder);
  }

  public static void StartRoot(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddPacketType(FlatBufferBuilder builder, fbs.Packet packetType) { builder.AddByte(0, (byte)packetType, 0); }
  public static void AddPacket(FlatBufferBuilder builder, int packetOffset) { builder.AddOffset(1, packetOffset, 0); }
  public static Offset<fbs.Root> EndRoot(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<fbs.Root>(o);
  }
  public static void FinishRootBuffer(FlatBufferBuilder builder, Offset<fbs.Root> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedRootBuffer(FlatBufferBuilder builder, Offset<fbs.Root> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class RootVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*PacketType*/, 1 /*fbs.Packet*/, 1, false)
      && verifier.VerifyUnion(tablePos, 4, 6 /*Packet*/, fbs.PacketVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
