// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fbs
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct S2C_CHAT_RES : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static S2C_CHAT_RES GetRootAsS2C_CHAT_RES(ByteBuffer _bb) { return GetRootAsS2C_CHAT_RES(_bb, new S2C_CHAT_RES()); }
  public static S2C_CHAT_RES GetRootAsS2C_CHAT_RES(ByteBuffer _bb, S2C_CHAT_RES obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public S2C_CHAT_RES __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(4); }
  public string Message { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetMessageBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetMessageBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetMessageArray() { return __p.__vector_as_array<byte>(6); }

  public static Offset<fbs.S2C_CHAT_RES> CreateS2C_CHAT_RES(FlatBufferBuilder builder,
      StringOffset nameOffset = default(StringOffset),
      StringOffset messageOffset = default(StringOffset)) {
    builder.StartTable(2);
    S2C_CHAT_RES.AddMessage(builder, messageOffset);
    S2C_CHAT_RES.AddName(builder, nameOffset);
    return S2C_CHAT_RES.EndS2C_CHAT_RES(builder);
  }

  public static void StartS2C_CHAT_RES(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(0, nameOffset.Value, 0); }
  public static void AddMessage(FlatBufferBuilder builder, StringOffset messageOffset) { builder.AddOffset(1, messageOffset.Value, 0); }
  public static Offset<fbs.S2C_CHAT_RES> EndS2C_CHAT_RES(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<fbs.S2C_CHAT_RES>(o);
  }
}


static public class S2C_CHAT_RESVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*Name*/, false)
      && verifier.VerifyString(tablePos, 6 /*Message*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
