// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fbs
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct S2C_USERLIST_RES : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static S2C_USERLIST_RES GetRootAsS2C_USERLIST_RES(ByteBuffer _bb) { return GetRootAsS2C_USERLIST_RES(_bb, new S2C_USERLIST_RES()); }
  public static S2C_USERLIST_RES GetRootAsS2C_USERLIST_RES(ByteBuffer _bb, S2C_USERLIST_RES obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public S2C_USERLIST_RES __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Name(int j) { int o = __p.__offset(4); return o != 0 ? __p.__string(__p.__vector(o) + j * 4) : null; }
  public int NameLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<fbs.S2C_USERLIST_RES> CreateS2C_USERLIST_RES(FlatBufferBuilder builder,
      VectorOffset nameOffset = default(VectorOffset)) {
    builder.StartTable(1);
    S2C_USERLIST_RES.AddName(builder, nameOffset);
    return S2C_USERLIST_RES.EndS2C_USERLIST_RES(builder);
  }

  public static void StartS2C_USERLIST_RES(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddName(FlatBufferBuilder builder, VectorOffset nameOffset) { builder.AddOffset(0, nameOffset.Value, 0); }
  public static VectorOffset CreateNameVector(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateNameVectorBlock(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateNameVectorBlock(FlatBufferBuilder builder, ArraySegment<StringOffset> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateNameVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<StringOffset>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartNameVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<fbs.S2C_USERLIST_RES> EndS2C_USERLIST_RES(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<fbs.S2C_USERLIST_RES>(o);
  }
}


static public class S2C_USERLIST_RESVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfStrings(tablePos, 4 /*Name*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
