// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fbs
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct S2C_CONNECT_RES : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static S2C_CONNECT_RES GetRootAsS2C_CONNECT_RES(ByteBuffer _bb) { return GetRootAsS2C_CONNECT_RES(_bb, new S2C_CONNECT_RES()); }
  public static S2C_CONNECT_RES GetRootAsS2C_CONNECT_RES(ByteBuffer _bb, S2C_CONNECT_RES obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public S2C_CONNECT_RES __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public bool BSuccess { get { int o = __p.__offset(4); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<fbs.S2C_CONNECT_RES> CreateS2C_CONNECT_RES(FlatBufferBuilder builder,
      bool b_success = false) {
    builder.StartTable(1);
    S2C_CONNECT_RES.AddBSuccess(builder, b_success);
    return S2C_CONNECT_RES.EndS2C_CONNECT_RES(builder);
  }

  public static void StartS2C_CONNECT_RES(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddBSuccess(FlatBufferBuilder builder, bool bSuccess) { builder.AddBool(0, bSuccess, false); }
  public static Offset<fbs.S2C_CONNECT_RES> EndS2C_CONNECT_RES(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<fbs.S2C_CONNECT_RES>(o);
  }
}


static public class S2C_CONNECT_RESVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*BSuccess*/, 1 /*bool*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
